In [4]:
import cv2

# Read & show img

In [5]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/1636632013154.jpg")     #Image read
cv2.imshow("Read_img",img)                                                  #Image show
cv2.waitKey(1)                                                              # waiting time in milisecound ,(0)till you not close the window
cv2.destroyAllWindows()                                                     # close all the window
#cv2.destroyWindow()                                                        # close one one window

# multiple image in 1 frame

In [6]:
import numpy as np

In [7]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [8]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
print(img)

[[[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 [[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 [[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 ...

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]]


In [9]:
# h-stack / v-stack fun for concatinate the matrix

In [10]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
re_img = cv2.resize(img,(300,300))
h = np.hstack((re_img,re_img))
v = np.vstack((h,h))
cv2.imshow("img",v)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# slideshow

In [11]:
import os

In [12]:
list_name = os.listdir(r"C:\Users\sumit\OneDrive\Desktop\cvimg")
list_name

['img1.png', 'img2.jpeg', 'img3.jpeg', 'img4.jpeg']

In [13]:
list_name = os.listdir(r"C:\Users\sumit\OneDrive\Desktop\cvimg")
for name in list_name:
    path = "C:\\Users\\sumit\\OneDrive\\Desktop\\cvimg"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(300,300))
    cv2.imshow("slidshow",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

# features 

In [14]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img3.jpeg")   #flag: 1 --> color,0 --> greyscale ,-1 --> unchanged
print(img.shape)
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows()

(159, 316, 3)


In [15]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img3.jpeg",0)   # it contain 0 channels.
print(img.shape)
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows()

(159, 316)


# Text over a img

In [16]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
re_img = cv2.resize(img,(400,500))

txt = cv2.putText(img=re_img,
text="Hero",
org=(50,80),                  #origin
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(255,0,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)

#reverse the text

txt = cv2.putText(img=txt,
text="Hero",
org=(50,80),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(0,0,255),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=True)

cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows()

# Draw line & box on images

In [17]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

new_img = cv2.line(img=old_img, pt1=(184,60), pt2=(240,60), color=(0,255,0), thickness=4, lineType=4)

cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [18]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

txt = cv2.putText(img=old_img,
text="Hero",
org=(50,80),                 
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(0,0,155),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)

new_img = cv2.rectangle(img=old_img, pt1=(184,10), pt2=(240,160), color=(0,255,0), thickness=4, lineType=4)     #(right,upper,left,down)

cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# Draw circle & ellipse on image

In [19]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

new_img = cv2.circle(img=old_img, center=(210,90), radius=70, color=(0,255,0), thickness=4, lineType=16)   # -1 thickness cover whole face
                     
cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [20]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

txt = cv2.putText(img=old_img,
text="Hero",
org=(50,80),                 
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(0,0,155),
thickness=3,
lineType=16,
bottomLeftOrigin=False)

new_img = cv2.ellipse(img=old_img, center=(210,90),axes=(50,100),angle=30,startAngle=0,endAngle=360, color=(0,255,0), thickness=4, lineType=16)
                     
cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# draw polygon on images

In [21]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

new_img = cv2.polylines(img=old_img, pts=[np.array([[100,100],[260,100],[260,250],[100,250],[250,180]])],
                        isClosed=True, color=(0,255,0), thickness=4, lineType=16)

cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# Arithmetic Operation on Images using OpenCV

In [28]:
img1 = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
img2 = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img3.jpeg")

img1 = cv2.resize(img1,(400,400))
img2 = cv2.resize(img2,(400,400))

new_img = cv2.addWeighted(img1,0.2,img2,1,1)
#new_img = cv2.subtract(img1,img2)

cv2.imshow("heros",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Bitwise operations on Binary images

In [38]:
img1 = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/b2.jpeg")
img2 = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/b1.png")

img1 = cv2.resize(img1,(300,300))
img2 = cv2.resize(img2,(300,300))

#new = cv2.bitwise_and(img1,img2)
#new = cv2.bitwise_or(img1,img2)
#new = cv2.bitwise_xor(img1,img2)
new=cv2.bitwise_not(img1)
new1=cv2.bitwise_not(img2)

h = np.hstack((img1,new))
h1 = np.hstack((img2,new1))

v=np.vstack((h,h1))

cv2.imshow("Bitwise",v)
cv2.waitKey(0)
cv2.destroyAllWindows()
              

# Edge detection

In [45]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img2.jpeg")
img = cv2.resize(img,(400,400))
print(img.shape)

new_img = cv2.Canny(img,50,50,apertureSize =5,L2gradient=True) #AppertureSize will be 3 to 7 only odd ones
print(new_img.shape)

cv2.imshow("with_edge",new_img)
cv2.imshow("Without_edge",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(400, 400, 3)
(400, 400)


# Image Scaling,rotation

In [49]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
re_img = cv2.resize(img,(400,400))

w,h =re_img.shape[0],re_img.shape[1]

m = cv2.getRotationMatrix2D((w/2,h/2),40,1)
new_img = cv2.warpAffine(re_img,m,(w,h))

cv2.imshow("img_after_rotation",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# img blurring