In [1]:
import cv2

# Read & show img

In [2]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/1636632013154.jpg")     #Image read
cv2.imshow("Read_img",img)                                                  #Image show
cv2.waitKey(1)                                                              # waiting time in milisecound ,(0)till you not close the window
cv2.destroyAllWindows()                                                     # close all the window
#cv2.destroyWindow()                                                        # close one one window

# multiple image in 1 frame

In [3]:
import numpy as np

In [4]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [5]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
print(img)

[[[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 [[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 [[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 ...

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]]


In [6]:
# h-stack / v-stack fun for concatinate the matrix

In [7]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
re_img = cv2.resize(img,(300,300))
h = np.hstack((re_img,re_img))
v = np.vstack((h,h))
cv2.imshow("img",v)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# slideshow

In [8]:
import os

In [11]:
list_name = os.listdir(r"C:\Users\sumit\OneDrive\Desktop\cvimg")
list_name

['img1.png', 'img2.jpeg', 'img3.jpeg', 'img4.jpeg']

In [16]:
list_name = os.listdir(r"C:\Users\sumit\OneDrive\Desktop\cvimg")
for name in list_name:
    path = "C:\\Users\\sumit\\OneDrive\\Desktop\\cvimg"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(300,300))
    cv2.imshow("slidshow",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

# features 

In [22]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img3.jpeg")   #flag: 1 --> color,0 --> greyscale ,-1 --> unchanged
print(img.shape)
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows()

(159, 316, 3)


In [23]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img3.jpeg",0)   # it contain 0 channels.
print(img.shape)
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows()

(159, 316)


# Text over a img

In [33]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
re_img = cv2.resize(img,(400,500))

txt = cv2.putText(img=re_img,
text="Hero",
org=(50,80),                  #origin
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(255,0,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)

#reverse the text

txt = cv2.putText(img=txt,
text="Hero",
org=(50,80),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(0,0,255),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=True)

cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows()

# Draw line & box on images

In [73]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

new_img = cv2.line(img=old_img, pt1=(184,60), pt2=(240,60), color=(0,255,0), thickness=4, lineType=4)

cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [76]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

txt = cv2.putText(img=old_img,
text="Hero",
org=(50,80),                 
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(0,0,155),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)

new_img = cv2.rectangle(img=old_img, pt1=(184,10), pt2=(240,160), color=(0,255,0), thickness=4, lineType=4)     #(right,upper,left,down)

cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# Draw circle & ellipse on image

In [96]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

new_img = cv2.circle(img=old_img, center=(210,90), radius=70, color=(0,255,0), thickness=4, lineType=16)   # -1 thickness cover whole face
                     
cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [100]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

txt = cv2.putText(img=old_img,
text="Hero",
org=(50,80),                 
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color=(0,0,155),
thickness=3,
lineType=16,
bottomLeftOrigin=False)

new_img = cv2.ellipse(img=old_img, center=(210,90),axes=(50,100),angle=30,startAngle=0,endAngle=360, color=(0,255,0), thickness=4, lineType=16)
                     
cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# draw polygon on images

In [ ]:
old_img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/img1.png")
old_img = cv2.resize(old_img,(400,500))

new_img = cv2.polylines(img=old_img, pts=[np.array([[100,100],[260,100],[260,250],[100,250],[250,180]])],
                        isClosed=True, color=(0,255,0), thickness=4, lineType=16)

cv2.imshow("img",new_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 