In [1]:
import cv2

# Read & show img

In [2]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/1636632013154.jpg")     #Image read
cv2.imshow("Read_img",img)                                                  #Image show
cv2.waitKey(1)                                                              # waiting time in milisecound ,(0)till you not close the window
cv2.destroyAllWindows()                                                     # close all the window
#cv2.destroyWindow()                                                        # close one one window

# multiple image in 1 frame

In [4]:
import numpy as np

In [10]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
re_img = cv2.resize(img,(400,500))
cv2.imshow("img",re_img)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

In [11]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
print(img)

[[[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 [[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 [[67 37 18]
  [67 37 18]
  [67 37 18]
  ...
  [41 28 14]
  [41 28 14]
  [41 28 14]]

 ...

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]

 [[26 66 64]
  [26 66 64]
  [26 66 64]
  ...
  [19 34 30]
  [19 34 30]
  [19 34 30]]]


In [ ]:
# h-stack / v-stack fun for concatinate the matrix

In [14]:
img = cv2.imread("C:/Users/sumit/OneDrive/Documents/bg.jpg")
re_img = cv2.resize(img,(300,300))
h = np.hstack((re_img,re_img))
v = np.vstack((h,h))
cv2.imshow("img",v)
cv2.waitKey(0)                                                              
cv2.destroyAllWindows() 

# slideshow