In [1]:
import cv2
import numpy as np

# Capture vedio from camera

In [3]:
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)  # external webcam at index 0

while True:
    ret, frame = cap.read()
    if not ret:
        print("❌ Failed to grab frame")
        break

    cv2.imshow("External Webcam", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# Slow & fast motion

In [8]:
cap = cv2.VideoCapture("C:/Users/sumit/OneDrive/Desktop/cvimg/Screen Recording 2025-07-31 224915.mp4")

while cap.isOpened():
    r,frame = cap.read()
    frame = cv2.resize(frame,(500,500))
    if r == True:
        cv2.imshow("slow & fast",frame)
        if cv2.waitKey(25) & 0xff == ord("p"):        # 25 se kam to fast motion and 25 se jayda to slow motion
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

# morphological operation

In [19]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/j.jpg")
img = cv2.resize(img,(500,500))

m = np.ones((5,5),np.uint8)                    #Creates a 5×5 matrix (2D array).Fills it with all 1s. 
print(m)                                       #np.uint8 (unsigned 8-bit integer: values range 0–255).

er = cv2.erode(img,m,iterations=1)             #cv2.erode() shrinks white areas and enlarges black areas
di = cv2.dilate(img,m,iterations=1)             #white (bright) regions grow and black (dark) regions shrink.


cv2.imshow("morphological",img)
cv2.imshow("morphological_ER",er)
cv2.imshow("morphological_di",di)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# opening method

In [37]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/o.jpg")
img = cv2.resize(img,(300,300))

k = np.ones((15,15),np.uint8)
                                                            #Opening = Erosion → then Dilation
op = cv2.morphologyEx(img,cv2.MORPH_OPEN,k,iterations=1)   #removes small white noise (tiny white spots on black background).

cv2.imshow("org",img)
cv2.imshow("opening",op)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Closing method

In [38]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/c.webp")
img = cv2.resize(img,(300,300))

k = np.ones((15,15),np.uint8)
                                                              #Closing = Dilation → then Erosion
cl = cv2.morphologyEx(img,cv2.MORPH_CLOSE,k,iterations=1)    #fills small black holes/gaps inside white regions, smooths contours.

cv2.imshow("org",img)
cv2.imshow("closing",cl)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Morphological gradient

In [29]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/j.jpg")
img = cv2.resize(img,(500,500))
k = np.ones((15,15),np.uint8)
                                                                  #Morphological Gradient = Dilation – Erosion
gr = cv2.morphologyEx(img,cv2.MORPH_GRADIENT,k,iterations=1)      #It highlights the edges/boundaries of objects.

cv2.imshow("org",img)
cv2.imshow("Gradient",gr)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Top hat

In [39]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/j.jpg")
img = cv2.resize(img,(500,500))
k = np.ones((35,35),np.uint8)                 
                                                                 #Top-hat = Original Image – Opening
th = cv2.morphologyEx(img,cv2.MORPH_TOPHAT,k,iterations=1)      #It extracts small bright regions that are smaller than the structuring element (kernel)

cv2.imshow("org",img)
cv2.imshow("TopHat",th)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Black Hat

In [36]:
img = cv2.imread("C:/Users/sumit/OneDrive/Desktop/cvimg/j.jpg")
img = cv2.resize(img,(500,500))
k = np.ones((15,15),np.uint8)
                                                                #Black-hat = Closing – Original
bh = cv2.morphologyEx(img,cv2.MORPH_BLACKHAT,k,iterations=1)    #It extracts dark regions (small black spots/lines) on a bright background.

cv2.imshow("org",img)
cv2.imshow("BlackHat",bh)
cv2.waitKey(0)
cv2.destroyAllWindows()