# Object Tracking & detection

In [1]:
import cv2
import numpy as np

In [5]:
cap = cv2.VideoCapture("D:/c data/cvimg/mixkit-man-and-woman-jogging-together-on-the-street-40881-hd-ready.mp4")
r,f = cap.read()
x,y,w,h = 290,55,250,885                                                                # ROI (Region of Interest):where the object is located in the first frame.
t = (x,y,w,h)                                                                           # track mai daaldiya
roi = f[y:y+h,x:x+w]
hsv_roi = cv2.cvtColor(roi,cv2.COLOR_BGR2HSV)                                           # convert it into HSV cause HSV is better for color tracking
mask = cv2.inRange(hsv_roi,np.array((0.,60.,32.)),np.array((180.,255.,255.,)))          # masking ki range function ke through
roi_hist = cv2.calcHist([hsv_roi],[0],mask,[180],[0,180])                               # histogram color ke through filter kiya.
                                                                                        # This histogram represents the color distribution of the object you want to trac
#Normalize the window
cv2.normalize(roi_hist,roi_hist,0,255,cv2.NORM_MINMAX)                                  # normalize kiya for stablity
tr = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT , 10,1 )                          # Defines termination criteria for the MeanShift algorithm:

while cap.isOpened():
    r,f = cap.read()
    if r == True:
        hsv_f = cv2.cvtColor(f , cv2.COLOR_BGR2HSV)
        d = cv2.calcBackProject([hsv_f],[0],roi_hist,[0,180],1)                         # backpropogation ke through vedio track ki 
        r,tp = cv2.meanShift(d,t,tr)                                                    # meanshift:object ke movement ke sath shift hoga , camshift: change shape according to object 
        x,y,w,h = tp
        final = cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),4)
        cv2.imshow("org",f)
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

# Corner detection using detection method

# via Harris Corner Detection method

In [14]:
img = cv2.imread("D:/c data/cvimg/shapes.png") 
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#print(gr)

# convert interger into float32 bits 
gr = np.float32(gr)

res = cv2.cornerHarris(gr,3,5,0.04)

res = cv2.dilate(res,None)
img[res>0.01*res.max()] = [0,0,255]

cv2.imshow("org",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img = cv2.imread("D:/c data/cvimg/green.jpeg")
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


# convert interger into float32 bits 
gr = np.float32(gr)

res = cv2.cornerHarris(gr,2,3,0.04)

res = cv2.dilate(res,None)
img[res>0.01*res.max()] = [0,0,255]

cv2.imshow("org",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Shi -Tomasi corner detection

In [23]:
img = cv2.imread("D:/c data/cvimg/shapes.png") 
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cr = cv2.goodFeaturesToTrack(gr,36,0.01,20)
cr = np.int64(cr)

for i in cr:
    x,y = i.ravel()
    cv2.circle(img,(x,y),5,(0,0,255),-1)

cv2.imshow("org",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# object detection using Haar-Cascade  (Face Detection)

In [36]:
img = cv2.imread("D:/c data/cvimg/group.jpeg")
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

f = cv2.CascadeClassifier("C:/Users/sumit/AppData/Local/Programs/Python/Python313/Lib/site-packages/cv2/data/haarcascade_frontalface_default.xml")
d = f.detectMultiScale(gry,1.1,2)         #it give you a points
print(d)

for (x,y,w,h) in d:
     cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)


cv2.imshow("org",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[175  39  26  26]
 [ 68  39  28  28]
 [  7  22  31  31]
 [ 98  42  25  25]
 [240  30  27  27]
 [134  31  30  30]
 [202  35  29  29]
 [ 70  20  39  39]]


In [37]:
#print(cv2.data.haarcascades)

In [40]:
img = cv2.imread("D:/c data/cvimg/dog mann.jfif")
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

f = cv2.CascadeClassifier("C:/Users/sumit/AppData/Local/Programs/Python/Python313/Lib/site-packages/cv2/data/haarcascade_frontalface_default.xml")
d = f.detectMultiScale(gry,1.6,2)         #it give you a points
print(d)

for (x,y,w,h) in d:
     cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)


cv2.imshow("org",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[202   7  61  61]]
